-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_emisor" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "nif" TEXT NOT NULL,
    "regimenFiscal" TEXT NOT NULL DEFAULT '01',
    "direccion" TEXT NOT NULL,
    "ciudad" TEXT NOT NULL,
    "provincia" TEXT NOT NULL,
    "cp" TEXT NOT NULL,
    "pais" TEXT NOT NULL DEFAULT 'ES',
    "telefono" TEXT,
    "email" TEXT,
    "web" TEXT,
    "sifNombre" TEXT NOT NULL DEFAULT 'SPG Facturación',
    "sifVersion" TEXT NOT NULL DEFAULT '1.0.0',
    "sifNif" TEXT NOT NULL DEFAULT 'B12345678',
    "productorNombre" TEXT,
    "productorDireccion" TEXT,
    "productorLocalidad" TEXT,
    "productorProvincia" TEXT,
    "productorCp" TEXT,
    "productorPais" TEXT DEFAULT 'España',
    "productorEmail" TEXT,
    "productorTelefono" TEXT,
    "seriePorDefecto" TEXT NOT NULL DEFAULT 'A',
    "ivaPorDefecto" DECIMAL NOT NULL DEFAULT 21.00,
    "metodoPagoPorDefecto" TEXT NOT NULL DEFAULT '02',
    "proximoNumeroFactura" INTEGER NOT NULL DEFAULT 1,
    "prefijoFactura" TEXT NOT NULL DEFAULT 'F',
    "proximoNumeroRectificativa" INTEGER NOT NULL DEFAULT 1,
    "prefijoRectificativa" TEXT NOT NULL DEFAULT 'R',
    "emailEnvioPorDefecto" BOOLEAN NOT NULL DEFAULT false,
    "emailPlantilla" TEXT,
    "smtpHost" TEXT,
    "smtpPort" INTEGER DEFAULT 587,
    "smtpUser" TEXT,
    "smtpPass" TEXT,
    "smtpFromName" TEXT,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
    "certificadoPath" TEXT,
    "certificadoPassword" TEXT,
    "backupAutomatico" BOOLEAN NOT NULL DEFAULT true,
    "backupPath" TEXT,
    "backupFrecuencia" TEXT NOT NULL DEFAULT 'semanal',
    "observacionesPorDefecto" TEXT,
    "pieDePagina" TEXT,
    "verifactuEnabled" BOOLEAN NOT NULL DEFAULT true,
    "activo" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_emisor" ("activo", "backupAutomatico", "backupFrecuencia", "backupPath", "certificadoPassword", "certificadoPath", "ciudad", "cp", "createdAt", "direccion", "email", "emailEnvioPorDefecto", "emailPlantilla", "id", "ivaPorDefecto", "metodoPagoPorDefecto", "nif", "nombre", "observacionesPorDefecto", "pais", "pieDePagina", "prefijoFactura", "productorCp", "productorDireccion", "productorEmail", "productorLocalidad", "productorNombre", "productorPais", "productorProvincia", "productorTelefono", "provincia", "proximoNumeroFactura", "regimenFiscal", "seriePorDefecto", "sifNif", "sifNombre", "sifVersion", "smtpFromName", "smtpHost", "smtpPass", "smtpPort", "smtpSecure", "smtpUser", "telefono", "updatedAt", "verifactuEnabled", "web") SELECT "activo", "backupAutomatico", "backupFrecuencia", "backupPath", "certificadoPassword", "certificadoPath", "ciudad", "cp", "createdAt", "direccion", "email", "emailEnvioPorDefecto", "emailPlantilla", "id", "ivaPorDefecto", "metodoPagoPorDefecto", "nif", "nombre", "observacionesPorDefecto", "pais", "pieDePagina", "prefijoFactura", "productorCp", "productorDireccion", "productorEmail", "productorLocalidad", "productorNombre", "productorPais", "productorProvincia", "productorTelefono", "provincia", "proximoNumeroFactura", "regimenFiscal", "seriePorDefecto", "sifNif", "sifNombre", "sifVersion", "smtpFromName", "smtpHost", "smtpPass", "smtpPort", "smtpSecure", "smtpUser", "telefono", "updatedAt", "verifactuEnabled", "web" FROM "emisor";
DROP TABLE "emisor";
ALTER TABLE "new_emisor" RENAME TO "emisor";
CREATE UNIQUE INDEX "Emisor_nif_key" ON "emisor"("nif");
CREATE TABLE "new_factura" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "numero" TEXT NOT NULL,
    "fechaEmision" DATETIME NOT NULL,
    "fechaOperacion" DATETIME,
    "estado" TEXT NOT NULL DEFAULT 'EMITIDA',
    "baseImponible" DECIMAL NOT NULL,
    "ivaImporte" DECIMAL NOT NULL,
    "irpfPorcentaje" DECIMAL,
    "irpfImporte" DECIMAL,
    "total" DECIMAL NOT NULL,
    "datosFiscales" TEXT NOT NULL,
    "detallesNormativa" TEXT,
    "hashCadenaAnterior" TEXT,
    "hashActual" TEXT,
    "xmlFirmadoPath" TEXT,
    "xmlFirmado" TEXT,
    "fechaHoraHitoGen" DATETIME,
    "sifNombre" TEXT,
    "sifVersion" TEXT,
    "sifNif" TEXT,
    "aeatEstado" TEXT NOT NULL DEFAULT 'PENDIENTE',
    "aeatCsv" TEXT,
    "aeatError" TEXT,
    "aeatEstadoAnulacion" TEXT,
    "aeatCsvAnulacion" TEXT,
    "tipoFactura" TEXT NOT NULL DEFAULT 'F1',
    "facturaRectificadaId" INTEGER,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "descuento" DECIMAL,
    "notas" TEXT,
    "metodoPago" TEXT,
    "pagada" BOOLEAN NOT NULL DEFAULT false,
    "importePagado" DECIMAL NOT NULL DEFAULT 0.00,
    "cuentaBancaria" TEXT,
    "clienteId" INTEGER NOT NULL,
    "emisorId" INTEGER NOT NULL,
    CONSTRAINT "factura_emisorId_fkey" FOREIGN KEY ("emisorId") REFERENCES "emisor" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "factura_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "cliente" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_factura" ("aeatCsv", "aeatError", "aeatEstado", "baseImponible", "clienteId", "createdAt", "cuentaBancaria", "datosFiscales", "descuento", "detallesNormativa", "emisorId", "estado", "fechaEmision", "fechaHoraHitoGen", "fechaOperacion", "hashActual", "hashCadenaAnterior", "id", "importePagado", "irpfImporte", "irpfPorcentaje", "ivaImporte", "metodoPago", "notas", "numero", "pagada", "sifNif", "sifNombre", "sifVersion", "total", "updatedAt", "xmlFirmado", "xmlFirmadoPath") SELECT "aeatCsv", "aeatError", "aeatEstado", "baseImponible", "clienteId", "createdAt", "cuentaBancaria", "datosFiscales", "descuento", "detallesNormativa", "emisorId", "estado", "fechaEmision", "fechaHoraHitoGen", "fechaOperacion", "hashActual", "hashCadenaAnterior", "id", "importePagado", "irpfImporte", "irpfPorcentaje", "ivaImporte", "metodoPago", "notas", "numero", "pagada", "sifNif", "sifNombre", "sifVersion", "total", "updatedAt", "xmlFirmado", "xmlFirmadoPath" FROM "factura";
DROP TABLE "factura";
ALTER TABLE "new_factura" RENAME TO "factura";
CREATE UNIQUE INDEX "Factura_numero_key" ON "factura"("numero");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
